version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: contas_postgres
    environment:
      POSTGRES_DB: contas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contas_backend
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/contas_db
      SECRET_KEY: sua-chave-secreta-aqui
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - contas-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contas_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - contas-network
    command: ["npm", "start"]

volumes:
  postgres_data:

networks:
  contas-network:
    driver: bridge